/*
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.locationiq.client.api;

import LocationIq.ApiException;
import com.locationiq.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AutocompleteApi
 */
@Ignore
public class AutocompleteApiTest {

    private final AutocompleteApi api = new AutocompleteApi();

    
    /**
     * 
     *
     * The Autocomplete API is a variant of the Search API that returns place predictions in response to an HTTP request.  The request specifies a textual search string and optional geographic bounds.  The service can be used to provide autocomplete functionality for text-based geographic searches, by returning places such as businesses, addresses and points of interest as a user types. The Autocomplete API can match on full words as well as substrings. Applications can therefore send queries as the user types, to provide on-the-fly place predictions.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void autocompleteTest() throws ApiException {
        String q = null;
        Integer normalizecity = null;
        Integer limit = null;
        String viewbox = null;
        Integer bounded = null;
        String countrycodes = null;
        String acceptLanguage = null;
        String tag = null;
        List<Object> response = api.autocomplete(q, normalizecity, limit, viewbox, bounded, countrycodes, acceptLanguage, tag);

        // TODO: test validations
    }
    
}
