/*
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.locationiq.client.api;

import LocationIq.ApiException;
import java.math.BigDecimal;
import com.locationiq.client.model.DirectionsDirections;
import com.locationiq.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DirectionsApi
 */
@Ignore
public class DirectionsApiTest {

    private final DirectionsApi api = new DirectionsApi();

    
    /**
     * Directions Service
     *
     * Finds the fastest route between coordinates in the supplied order.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directionsTest() throws ApiException {
        String coordinates = null;
        String bearings = null;
        String radiuses = null;
        String generateHints = null;
        String approaches = null;
        String exclude = null;
        BigDecimal alternatives = null;
        String steps = null;
        String annotations = null;
        String geometries = null;
        String overview = null;
        String continueStraight = null;
        DirectionsDirections response = api.directions(coordinates, bearings, radiuses, generateHints, approaches, exclude, alternatives, steps, annotations, geometries, overview, continueStraight);

        // TODO: test validations
    }
    
}
