/*
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.locationiq.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * DirectionsNearestWaypoints
 */

public class DirectionsNearestWaypoints {
  public static final String SERIALIZED_NAME_NODES = "nodes";
  @SerializedName(SERIALIZED_NAME_NODES)
  private List<BigDecimal> nodes = null;

  public static final String SERIALIZED_NAME_DISTANCE = "distance";
  @SerializedName(SERIALIZED_NAME_DISTANCE)
  private BigDecimal distance;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private List<BigDecimal> location = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public DirectionsNearestWaypoints nodes(List<BigDecimal> nodes) {
    
    this.nodes = nodes;
    return this;
  }

  public DirectionsNearestWaypoints addNodesItem(BigDecimal nodesItem) {
    if (this.nodes == null) {
      this.nodes = new ArrayList<BigDecimal>();
    }
    this.nodes.add(nodesItem);
    return this;
  }

   /**
   * Get nodes
   * @return nodes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<BigDecimal> getNodes() {
    return nodes;
  }


  public void setNodes(List<BigDecimal> nodes) {
    this.nodes = nodes;
  }


  public DirectionsNearestWaypoints distance(BigDecimal distance) {
    
    this.distance = distance;
    return this;
  }

   /**
   * Get distance
   * @return distance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getDistance() {
    return distance;
  }


  public void setDistance(BigDecimal distance) {
    this.distance = distance;
  }


  public DirectionsNearestWaypoints location(List<BigDecimal> location) {
    
    this.location = location;
    return this;
  }

  public DirectionsNearestWaypoints addLocationItem(BigDecimal locationItem) {
    if (this.location == null) {
      this.location = new ArrayList<BigDecimal>();
    }
    this.location.add(locationItem);
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<BigDecimal> getLocation() {
    return location;
  }


  public void setLocation(List<BigDecimal> location) {
    this.location = location;
  }


  public DirectionsNearestWaypoints name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DirectionsNearestWaypoints directionsNearestWaypoints = (DirectionsNearestWaypoints) o;
    return Objects.equals(this.nodes, directionsNearestWaypoints.nodes) &&
        Objects.equals(this.distance, directionsNearestWaypoints.distance) &&
        Objects.equals(this.location, directionsNearestWaypoints.location) &&
        Objects.equals(this.name, directionsNearestWaypoints.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nodes, distance, location, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DirectionsNearestWaypoints {\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

