/*
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.locationiq.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Address
 */
public class AddressTest {
    private final Address model = new Address();

    /**
     * Model tests for Address
     */
    @Test
    public void testAddress() {
        // TODO: test Address
    }

    /**
     * Test the property 'houseNumber'
     */
    @Test
    public void houseNumberTest() {
        // TODO: test houseNumber
    }

    /**
     * Test the property 'road'
     */
    @Test
    public void roadTest() {
        // TODO: test road
    }

    /**
     * Test the property 'residential'
     */
    @Test
    public void residentialTest() {
        // TODO: test residential
    }

    /**
     * Test the property 'borough'
     */
    @Test
    public void boroughTest() {
        // TODO: test borough
    }

    /**
     * Test the property 'neighbourhood'
     */
    @Test
    public void neighbourhoodTest() {
        // TODO: test neighbourhood
    }

    /**
     * Test the property 'quarter'
     */
    @Test
    public void quarterTest() {
        // TODO: test quarter
    }

    /**
     * Test the property 'hamlet'
     */
    @Test
    public void hamletTest() {
        // TODO: test hamlet
    }

    /**
     * Test the property 'suburb'
     */
    @Test
    public void suburbTest() {
        // TODO: test suburb
    }

    /**
     * Test the property 'island'
     */
    @Test
    public void islandTest() {
        // TODO: test island
    }

    /**
     * Test the property 'village'
     */
    @Test
    public void villageTest() {
        // TODO: test village
    }

    /**
     * Test the property 'town'
     */
    @Test
    public void townTest() {
        // TODO: test town
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'cityDistrict'
     */
    @Test
    public void cityDistrictTest() {
        // TODO: test cityDistrict
    }

    /**
     * Test the property 'county'
     */
    @Test
    public void countyTest() {
        // TODO: test county
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'stateDistrict'
     */
    @Test
    public void stateDistrictTest() {
        // TODO: test stateDistrict
    }

    /**
     * Test the property 'postcode'
     */
    @Test
    public void postcodeTest() {
        // TODO: test postcode
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'stateCode'
     */
    @Test
    public void stateCodeTest() {
        // TODO: test stateCode
    }

}
