/*
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.locationiq.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.locationiq.client.model.DirectionsMatrixSources;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DirectionsMatrix
 */
public class DirectionsMatrixTest {
    private final DirectionsMatrix model = new DirectionsMatrix();

    /**
     * Model tests for DirectionsMatrix
     */
    @Test
    public void testDirectionsMatrix() {
        // TODO: test DirectionsMatrix
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'distances'
     */
    @Test
    public void distancesTest() {
        // TODO: test distances
    }

    /**
     * Test the property 'fallbackSpeedCells'
     */
    @Test
    public void fallbackSpeedCellsTest() {
        // TODO: test fallbackSpeedCells
    }

    /**
     * Test the property 'sources'
     */
    @Test
    public void sourcesTest() {
        // TODO: test sources
    }

    /**
     * Test the property 'destinations'
     */
    @Test
    public void destinationsTest() {
        // TODO: test destinations
    }

}
