/*
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.locationiq.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.locationiq.client.model.Address;
import com.locationiq.client.model.Matchquality;
import com.locationiq.client.model.Namedetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Location
 */
public class LocationTest {
    private final Location model = new Location();

    /**
     * Model tests for Location
     */
    @Test
    public void testLocation() {
        // TODO: test Location
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'placeId'
     */
    @Test
    public void placeIdTest() {
        // TODO: test placeId
    }

    /**
     * Test the property 'licence'
     */
    @Test
    public void licenceTest() {
        // TODO: test licence
    }

    /**
     * Test the property 'osmType'
     */
    @Test
    public void osmTypeTest() {
        // TODO: test osmType
    }

    /**
     * Test the property 'osmId'
     */
    @Test
    public void osmIdTest() {
        // TODO: test osmId
    }

    /**
     * Test the property 'boundingbox'
     */
    @Test
    public void boundingboxTest() {
        // TODO: test boundingbox
    }

    /**
     * Test the property 'lat'
     */
    @Test
    public void latTest() {
        // TODO: test lat
    }

    /**
     * Test the property 'lon'
     */
    @Test
    public void lonTest() {
        // TODO: test lon
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'propertyClass'
     */
    @Test
    public void propertyClassTest() {
        // TODO: test propertyClass
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'importance'
     */
    @Test
    public void importanceTest() {
        // TODO: test importance
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'namedetails'
     */
    @Test
    public void namedetailsTest() {
        // TODO: test namedetails
    }

    /**
     * Test the property 'matchquality'
     */
    @Test
    public void matchqualityTest() {
        // TODO: test matchquality
    }

}
